### ISSUE TITLE
matchutils missing in the public repo

### ISSUE THREAD

**Issue by smartsammler** [Archman/beamline#1]
The import of ParseParams, BeamMatch, FELSimulator and parseLattice fails, because matchutils can't be imported, because it is missing in the github repo.

**Comment by zhangt58** [comment]
Yes, 'matchutils.py' has been missed, the package in PyPI works because 'matchutils.pyc' file exist, Thanks!

**Comment by zhangt58** [comment]
@smartsammler If it works now, I think this issue could be closed, thanks.
