### ISSUE TITLE
PEP8/FLAKE8 compatibility

### ISSUE THREAD

**Issue by smartsammler** [Archman/beamline#6]
There's no document for the preferred coding style, therefore I ask you if I might submit pull requests with changes (most often done by my editor) to make the modules [PEP 8](https://www.python.org/dev/peps/pep-0008/) conform and make [pycodestyle](https://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes)  and [Flake8](https://flake8.readthedocs.io/en/latest/) warn one less.
Typical changes would be no space at the end of a line, spaces after commas, no unnecessary blank lines, etc.

**Comment by zhangt58** [comment]
I'm following PEP-8 for most part of the code, maybe some code is not, I suggest you only apply the editor's flavor to the code that would be changed/updated.

**Comment by smartsammler** [comment]
Ok, that's good.

**Comment by archman** [comment]
I just added you as a collaborator of this repo, if you'd like to accept the invitation, thanks.
